### ISSUE TITLE
I receive empty PDF

### ISSUE THREAD

**Issue by jsprasu** [zeplin/zeplin-html-to-pdf#17]
Hi.

When I download the repo and upload to the AWS Lambda function, I get an empty PDF file as the base64 encoded string. Please help me to resolve this issue. I am using Lambda Node 4.3 as runtime.

Thank you.

**Comment by dorukgunes** [comment]
@jsprasu we released a major update on this function, can you please try with a runtime nodejs6.10 or higher. Feel free to open again if you encounter the same problem.
