### ISSUE TITLE
Incorrect Characters in Output PDF

### ISSUE THREAD

**Issue by micah500** [zeplin/zeplin-html-to-pdf#24]
Hi there,

Although HTML is accepted by the function, once decoding the output data no text appears, instead I just see black squares where the characters should be. It's like I've got the character encoding wrong or something! This running in AWS Lambda on Node 12.x.

Here's an example of the input:
`{
  "html": "<!DOCTYPE html><html><head><title>HTML Document</title></head><body>Content <h1>title here</h1> More info here</body></html>"
}`

And the output:
`{
  "data": "JVBERi0xLjQKMSAwIG9iago8PAovVGl0bGUgKP7/AEgAVABNAEwAIABEAG8AYwB1AG0AZQBuAHQpCi9DcmVhdG9yICj+/wB3AGsAaAB0AG0AbAB0AG8AcABkAGYAIAAwAC4AMQAyAC4AMwAtAGQAZQB2AC0ANwA5AGYAZgA1ADEAZSkKL1Byb2R1Y2VyICj+/wBRAHQAIAA0AC4AOAAuADcpCi9DcmVhdGlvbkRhdGUgKEQ6MjAyMDA0MDgwODAxNTZaKQo+PgplbmRvYmoKMyAwIG9iago8PAovVHlwZSAvRXh0R1N0YXRlCi9TQSB0cnVlCi9TTSAwLjAyCi9jYSAxLjAKL0NBIDEuMAovQUlTIGZhbHNlCi9TTWFzayAvTm9uZT4+CmVuZG9iago0IDAgb2JqClsvUGF0dGVybiAvRGV2aWNlUkdCXQplbmRvYmoKNiAwIG9iagpbMCAvWFlaIDM0LjA3OTk5OTkgIAo3ODIuOTU5OTk5ICAwXQplbmRvYmoKNyAwIG9iago8PAovX19XS0FOQ0hPUl8yIDYgMCBSCj4+CmVuZG9iago5IDAgb2JqCjw8L1RpdGxlICj+/wB0AGkAdABsAGUAIABoAGUAcgBlKQogIC9QYXJlbnQgOCAwIFIKICAvRGVzdCAvX19XS0FOQ0hPUl8yCiAgL0NvdW50IDAKPj4KZW5kb2JqCjggMCBvYmoKPDwvVHlwZSAvT3V0bGluZXMgL0ZpcnN0IDkgMCBSCi9MYXN0IDkgMCBSPj4KZW5kb2JqCjEwIDAgb2JqCjw8Ci9UeXBlIC9DYXRhbG9nCi9QYWdlcyAyIDAgUgovT3V0bGluZXMgOCAwIFIKL1BhZ2VNb2RlIC9Vc2VPdXRsaW5lcwovRGVzdHMgNyAwIFIKPj4KZW5kb2JqCjUgMCBvYmoKPDwKL1R5cGUgL1BhZ2UKL1BhcmVudCAyIDAgUgovQ29udGVudHMgMTEgMCBSCi9SZXNvdXJjZXMgMTMgMCBSCi9Bbm5vdHMgMTQgMCBSCi9NZWRpYUJveCBbMCAwIDU5NSA4NDJdCj4+CmVuZG9iagoxMyAwIG9iago8PAovQ29sb3JTcGFjZSA8PAovUENTcCA0IDAgUgovQ1NwIC9EZXZpY2VSR0IKL0NTcGcgL0RldmljZUdyYXkKPj4KL0V4dEdTdGF0ZSA8PAovR1NhIDMgMCBSCj4+Ci9QYXR0ZXJuIDw8Cj4+Ci9Gb250IDw8Cj4+Ci9YT2JqZWN0IDw8Cj4+Cj4+CmVuZG9iagoxNCAwIG9iagpbIF0KZW5kb2JqCjExIDAgb2JqCjw8Ci9MZW5ndGggMTIgMCBSCi9GaWx0ZXIgL0ZsYXRlRGVjb2RlCj4+CnN0cmVhbQp4nN2YPY8TMRRFe/+KqZGY+GvGM3UKJAqkUQoKRIGCYIU2K6It+Pt4bC++94W3BVooyEqb+GR8j+PYnqcc3pw+DV8fh8Px9H04t+fjydjRzrY+hv3vNQK/jMHXl4sL45zW/BjOF3MdrmYzW/6/P1+Nm0vn9pQveNLU0MfzgznUAZhKTsd3+dWPwQ9vc+vb8OFjfvrcMvcLLmZZ5zwWa13IzXtsumAXN+ZRusytbO4X35n3r4aHfWB+XMoHcHWA3Pzzgd6+6fub12dStzJf+vvO+jHWEcJgL8bPS21F5PfE0zqWb8tnjjkax5w7E2yql0U2xxTGsiIS90COBszROJun3LY3houZ01LG6iz3QI4GzNE4m5ObS5sNee0toXTfFxv2QI4GzNE4m1dflqwwXPL3syzjb74f5GjAHI2z2Tk/1+kTZr/WpjQDp5UEORoX5hBcnT5hjmsqg/XCDJwMkKNxNn+pp9RLHga037d/ciBMk60vF96WwGlbwhqgja9xyqFtSWbYBNQDOBkgR+PCDJeRGZYi9QBOBmhoXJhhCbE5tWnywtw5z2rP0bg0p2jLZ/Bs9q5NkxgrcDb0HI0Ls3etLWbbT62/NHdOBsjRuDRP9Z5+Y17bLEVh7pwNPUfj0rzOa7kusjmENkvCDJwNPUfjwhxCO7ImYU6tNQlz52SAHI1Lc1pqrSDM0bVZmsVJ0jkbeo7Ghfn/OH7hlBH12C/O9Vic6jch6y6NY46ox8BM9Rj0QI4GzNE4m6leAjPVY9ADORowR+NspnoJzFSPQQ/kaMAcjbOZ6iUwUz0GPZCjAXM0zmaql9CM9RiagdNKghyNCzPWS2jGegzNwMkAORoX5inMZfa8MPfbKZuBkwFyNC7M/TbI5rVtB2kGTgbI0bgwr3G6nVW6wfNJApwMkKNxNsMNmM2hbQdpBo4GzNG4MIdpKpdJcy8h2AycDJCjcWHut342p7Yb5LkNnAyQo3FhTnNspQKbe/HCZuBkgByNs/nv32affvN5ud97rs9Lt2EzPwEZkLYrCmVuZHN0cmVhbQplbmRvYmoKMTIgMCBvYmoKNzc1CmVuZG9iagoyIDAgb2JqCjw8Ci9UeXBlIC9QYWdlcwovS2lkcyAKWwo1IDAgUgpdCi9Db3VudCAxCi9Qcm9jU2V0IFsvUERGIC9UZXh0IC9JbWFnZUIgL0ltYWdlQ10KPj4KZW5kb2JqCnhyZWYKMCAxNQowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMDkgMDAwMDAgbiAKMDAwMDAwMTg2MiAwMDAwMCBuIAowMDAwMDAwMjA3IDAwMDAwIG4gCjAwMDAwMDAzMDIgMDAwMDAgbiAKMDAwMDAwMDY5NCAwMDAwMCBuIAowMDAwMDAwMzM5IDAwMDAwIG4gCjAwMDAwMDAzOTAgMDAwMDAgbiAKMDAwMDAwMDUzMiAwMDAwMCBuIAowMDAwMDAwNDMxIDAwMDAwIG4gCjAwMDAwMDA1OTIgMDAwMDAgbiAKMDAwMDAwMDk5MSAwMDAwMCBuIAowMDAwMDAxODQyIDAwMDAwIG4gCjAwMDAwMDA4MTUgMDAwMDAgbiAKMDAwMDAwMDk3MSAwMDAwMCBuIAp0cmFpbGVyCjw8Ci9TaXplIDE1Ci9JbmZvIDEgMCBSCi9Sb290IDEwIDAgUgo+PgpzdGFydHhyZWYKMTk2MAolJUVPRgo="
}`

Am I missing something super obvious? Any help is greatly appreciated.

Micah

[download.pdf](https://github.com/zeplin/zeplin-html-to-pdf/files/4449077/download.pdf)

**Comment by staffe** [comment]
I had the exact same issue as described above (Node 12.x) but I solved it by adding the environment variable `FONTCONFIG_PATH=/var/task/fonts` to the lambda function

**Comment by micah500** [comment]
Hey @staffe, that worked perfectly! Thank you so much for taking the time to reply here and let me know. Micah
