### ISSUE TITLE
When options are set getting Error: wkhtmltopdf process exited with code 1

### ISSUE THREAD

**Issue by gduggirala** [zeplin/zeplin-html-to-pdf#4]
The following is the payload and the options that are set

`["--page-size Letter","--orientation Portrait","--margin-bottom 1","--margin-top 1","--margin-right 1","--margin-left 1"]`

And the code is changed to send these options as second param..

```
wkhtmltopdf(html, event.options)
        .then(function(buffer) {
            callback(null, {
                data: buffer.toString("base64")
            });
        }).catch(function(error) {
            callback(errorUtil.createErrorResponse(500, "Internal server error", error));
        });
```
And I am getting the following error when executed in Lamda env.
`
{"errorMessage":"[ServerError] Internal server error\nError: wkhtmltopdf process exited with code 1\n    at ChildProcess.<anonymous> (/var/task/utils/wkhtmltopdf.js:16:24)\n    at emitTwo (events.js:87:13)\n    at ChildProcess.emit (events.js:172:7)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)"}`

Thank in advance.

**Comment by gduggirala** [comment]
I think I figured out the resolution for the issue.

Change the line which spawn's the process of wkhtmltopdf 

from

`var proc = spawn("/bin/sh", ["-o", "pipefail", "-c", "wkhtmltopdf - - " + options.join(" ") + " | cat"]);`

to 

`var proc = spawn("/bin/sh", ["-o", "pipefail", "-c", "wkhtmltopdf " + options.join(" ") + " - -  | cat"]);`

I see that the resultant PDF which is being generated is honouring the options passed.

**Comment by williamxsp** [comment]
Where have you changed this?

**Comment by Samerkassem** [comment]
Yes, where??? in that in the main library??
